_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  WEIGHTS: "torchvision-R-101.pkl"
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
  SparseRCNN:
    NUM_PROPOSALS: 100
    NUM_CLASSES: 80
DATASETS:
  TRAIN: ("coco_2017_train",)
#  TEST:  ("coco_2017_val",)
  TEST:  ("coco_2017_test-dev",)
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
INPUT:
  CROP:
    ENABLED: False
  FORMAT: "RGB"
OUTPUT_DIR: /media/lab308/c06b8ee9-baa0-4d90-845c-51b2bdc44856/SparseR-CNN1/projects/SparseR-CNN/output/test101_300